blok1/urls.py
from django.urls import path, include, re_path
from blok1 import views

urlpatterns = [
    path('', views.Home, name='Home'),
    re_path('Registration/', views.Registration, name='Registration'),
    re_path('Verify/(?P<uuid>[a-z0-9\-]+)/', views.Verify, name='Verify'),
    re_path('list_currencies_sell/', views.list_currencies_sell, name='list_currencies_sell'),
    re_path('form_exchange/(?P<currence_purchase_id>[\w-]+)/(?P<currence_sell_id>[\w-]+)', views.form_exchange, name='form_exchange'),
    re_path('Exchange_currency_result/(?P<currency_by_id>[\w-]+)/(?P<currency_sell_id>[\w-]+)', views.Exchange_currency_result, name='Exchange_currency_result'),
    re_path('Exchange_currency_select_by/', views.Exchange_currency_select_by, name='Exchange_currency_select_by'),
    re_path('Exchange_currency_bid/(?P<currency_by_id>[\w-]+)/(?P<currency_sell_id>[\w-]+)', views.Exchange_currency_bid, name='Exchange_currency_bid'),
    re_path('Exchange_currency_bid_info/(?P<request_id>[\w-]+)/(?P<market>[\w-]+)/(?P<name_bank_buy>[\w-]+)', views.Exchange_currency_bid_info, name='Exchange_currency_bid_info'),
    re_path('Exchange_currency_pay/(?P<request_id>[\w-]+)', views.Exchange_currency_pay, name='Exchange_currency_pay'),
    re_path('Exchange_request_del/', views.Exchange_request_del, name='Exchange_request_del'),
    re_path('Site_maintenance_check/', views.Site_maintenance_check, name='Site_maintenance_check'),
    re_path('Site_maintenance_active/', views.Site_maintenance_active, name='Site_maintenance_active'),
    re_path('Site_maintenance_deactivate/', views.Site_maintenance_deactivate, name='Site_maintenance_deactivate'),


]

blok2/urls.py
from django.urls import path, include, re_path
from blok2 import views






urlpatterns = [
    path('', views.Account, name='Account'),
    re_path('Account_user/', views.Account_user, name='Account_user'),
    re_path('Account_user_pass/', views.Account_user_pass, name='Account_user_pass'),
    re_path('MarketExchange/', views.MarketExchange, name='MarketExchange'),
    re_path('NameCurrency/', views.NameCurrency, name='NameCurrency'),
    re_path('FiatWallet/', views.FiatWallet, name='FiatWallet'),
    re_path('BalanceCurrency/', views.BalanceCurrency, name='BalanceCurrency'),
    re_path('PricesCurrency/', views.PricesCurrency, name='PricesCurrency'),
    re_path('FNews/', views.FNews, name='FNews'),
    re_path('FNewsImage/', views.FNewsImage, name='FNewsImage'),
    re_path('ExchangeList/', views.ExchangeList, name='ExchangeList'),
    re_path('Users_clients/', views.Users_clients, name='Users_clients'),
    re_path('Users_clients_active/', views.Users_clients_active, name='Users_clients_active'),
    re_path('Users_clients_deactivate/', views.Users_clients_deactivate, name='Users_clients_deactivate'),
    re_path('Exchange_operations/', views.Exchange_operations, name='Exchange_operations'),
    re_path('Exchange_operations_client/', views.Exchange_operations_client, name='Exchange_operations_client'),

    #re_path('NameCurrencyTrading/', views.NameCurrencyTrading, name='NameCurrencyTrading'),



#    re_path('Print_report/', views.Print_report, name='Print_report'),
#    re_path('Print_pdf/', views.Print_pdf, name='Print_pdf'),



]

chgskv/urls.py
# blok1 - домашняя страница(верх,основа,футер), основное меню, меню регистрации пользователей(jqury,метод ajax),
#         верификация по email, модель(база данных) пользователей(встроенная user плюс дополнительная profile свои поля)

# blok2 - кабинет пользователя(просмотр,редактирование,удаление данных пользователя), администратора(просмотр,
#         редактирование,удаление справочников сайта), все модели(базы данных) сайта кроме пользователей(blok1)

# blok3 - главная страница обмена, новости, весь функционал


from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

# для таблицы плагина datatables
from rest_framework.routers import DefaultRouter
from blok2.views import MarketExchange_ViewSet, NameCurrency_ViewSet, FiatWallet_ViewSet, PricesCurrency_ViewSet, BalanceCurrency_ViewSet, News_ViewSet, NewsImage_ViewSet, ExchangeList_ViewSet  #NameCurrencyTrading_ViewSet
router = DefaultRouter()

# табл БД Market_Exchange в blok2/models.py, MarketExchange_ViewSet класс для обмена данными
# методом ajax c скриптом js/table_market_exchange.js
router.register('Market_Exchange', MarketExchange_ViewSet)

# табл БД Name_Currency в blok2/models.py, NameCurrency_ViewSet класс для обмена данными
# методом ajax c скриптом js/table_name_currency.js
router.register('Name_Currency', NameCurrency_ViewSet)

# табл БД Fiat_Wallet в blok2/models.py, FiatWallet_ViewSet класс для обмена данными
# методом ajax c скриптом js/table_fiat_wallet.js
router.register('Fiat_Wallet', FiatWallet_ViewSet)

# табл БД Prices_Currency в blok2/models.py, PricesCurrency_ViewSet класс для обмена данными
# методом ajax c скриптом js/table_prices_currency.js
router.register('Prices_Currency', PricesCurrency_ViewSet)

# табл БД Balance_Currency в blok2/models.py, BalanceCurrency_ViewSet класс для обмена данными
# методом ajax c скриптом js/table_balance_currency.js
router.register('Balance_Currency', BalanceCurrency_ViewSet)

# табл БД News в blok2/models.py, News_ViewSet класс для обмена данными
# методом ajax c скриптом js/table_news.js
router.register('News', News_ViewSet)

# табл БД NewsImage в blok2/models.py, NewsImage_ViewSet класс для обмена данными
# методом ajax c скриптом js/table_newsimage.js
router.register('NewsImage', NewsImage_ViewSet)

# табл БД Exchange_List в blok2/models.py, ExchangeList_ViewSet класс для обмена данными
# методом ajax c скриптом js/table_exchange_list.js
router.register('Exchange_List', ExchangeList_ViewSet)

# этот справочник стал не нужен так как изменилась логика загрузки курсов валют
# табл БД Name_Currency_Trading в blok2/models.py, NameCurrencyTrading_ViewSet класс для обмена данными
# методом ajax c скриптом js/table_name_currency_trading.js
#router.register('Name_Currency_Trading', NameCurrencyTrading_ViewSet)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blok1.urls')),
    path('Kabinet/', include('blok2.urls')),
    path('api/', include(router.urls)), # для таблицы плагина datatables, api фрэмворка rest framework
    path('Obmen/', include('blok3.urls')),
    path('Poloniex/', include('blok4.urls')),
    path('celery-progress/', include('celery_progress.urls')), # для celeri progressbar

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
                 + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Поиск медиа файлов по путям заданным в переменных STATIC_URL,STATIC_ROOT,MEDIA_URL,MEDIA_ROOT файла settings.py

blok1/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid
from django.db.models import signals
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse
from django.core.exceptions import ValidationError


# Create your models here.

# Наша модель(БД) именем Profile встроенной базы пользователей django с дополнительными полями, метод OneToOneField
# Доп поля по ключу user_id встроенной БД(из админки) пользователей user
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Список дополнительных полей
    session_key = models.CharField(max_length=128, blank=True, null=True, default=None)  # ключ сессии, для контроля сторонних(хакерских) запросов, присваивается пользователю при посещении сайта, если заходит с другого броузера или компьютера то ключ изменится
    birth_date = models.DateField(null=True, blank=True) # день рождения
    location = models.CharField(max_length=30, blank=True) # Последний ip пользователя
    phone = models.CharField(max_length=30, blank=True) # Телефон пользователя
    active = models.BooleanField(default=False) # Поле для активации пользователя по email
    verification_uuid = models.UUIDField('Unique Verification UUID', default=uuid.uuid4) # Поле для проверки уникальности верификации по email
    created = models.DateTimeField(auto_now_add=True, auto_now=False)  # Поле дата когда пользователь зарегистрировался
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)  # Поле дата когда пользователь заходил последний раз

# Применяем функцию create_or_update_user_profile  к нашей БД Profile(по сигналу post_save
# при изменении в таблице БД User из django.contrib.auth.models делаются изменения в таблице БД Profile, т.е. так
# получается связка основной таблицы пользователей User и расширенной Profile  с дополнительными полями)
@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        if not instance.profile.active:
            try:
                subject = 'Активация учетной записи на zobmen.top'
                msg = 'Добрый день! Для активации регистрации перейдите по этой ссылке: https://zobmen.top%s' % reverse('Verify', kwargs={'uuid': str(instance.profile.verification_uuid)}) # локально по этой ссылке: http://127.0.0.1:8000%s'
                send_mail(
                    subject,
                    msg,
                    settings.EMAIL_HOST_USER, # EMAIL_HOST_USER задан в settings.py
                    [instance.email],
                    fail_silently=False,
                )
            except Exception as e:
                print("Ошибка отправки email: ", e)

    instance.profile.save()

# перенес в функцию create_user_profile чтобы не делать вторую функцию по сигналу post_save(упростил)
#@receiver(post_save, sender=User)
#def save_user_profile(sender, instance, **kwargs):
#    instance.profile.save()

 # Отправка ссылки подтверждения по email для активации пользователя(перенес в функцию create_user_profile, т.к.
 # дублировалась отправка сообщения )
#def user_post_save(sender, instance, signal, *args, **kwargs):
    # post_url = request.build_absolute_uri()
    # если поле active = False в таблице БД Profile то отправляем ссылку на email
#    if not instance.profile.active:
#        subject = 'Активация учетной записи Chgskv.com'
#        msg = 'Добрый день! Для активации регистрации перейдите по этой ссылке: http://127.0.0.1:8000%s' % reverse('Verify', kwargs={'uuid': str(instance.profile.verification_uuid)})
#        send_mail(
#            subject,
#            msg,
#            settings.EMAIL_HOST_USER,
#            [instance.email],
#            fail_silently=False,
#        )
#signals.post_save.connect(user_post_save, sender=User)


class Site_maintenance(models.Model):
    maintenance = models.BooleanField(default=False) # Поле для активации перехода сайта в техобслуживание
    created = models.DateTimeField(auto_now_add=True, auto_now=False)  # Поле дата создания записи
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)  # Поле дата изменения записи

    # _str_(self) - метод, вызываемый функциями str, print и format. Возвращает строковое представление объекта
    # Используем этот метод для удобного отображения информации полей в django админке
    # для отображения в админке, регистрируем в admin.py
    #def __str__(self):
    #    return "Техобслуживание {}".format(self.maintenance)

    # Для отображения наименований в django админке
    class Meta:
        verbose_name = 'БД Техобслуживание сайта'
        verbose_name_plural = 'Записи в БД Site_maintenance'

blok2/forms.py
from django import forms


# Задаем поля без значений first_name,last_name,location и birth_date формы и передаем в файл views.py
# (в views.py импортируем from .forms import ContactForm), не использую т.к. использую метод ajax в scripts_izreg.js
class ContactForm(forms.Form):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    #location = forms.CharField(required=True)
    birth_date = forms.DateField(required=True)

class ContactFormPass(forms.Form):
    password = forms.CharField(required=True)
    password1 = forms.CharField(required=True)

blok2/templates/account.html
<!-- Страница кабинета администратора или пользователя(просмотр,редактирование,удаление учетных данных, справочников)-->
{% extends 'base.html' %} <!-- наследуемся(вставка в base блока content) от основного шаблона base.html (верх,основа,футер) -->
{% load static %} <!-- обращаемся в каталог static где наши jpg и css -->


{% block content %}
<!--    <div class="wrapper-content"> -->
        {% if user.is_superuser == 1 %}
              {% include 'navbar_kaba.html' %} <!-- Меню администратора -->
        {% else %}
              {% include 'navbar_kab.html' %} <!-- Меню пользователя -->
        {% endif %}

<!--    </div>  -->

    <div class="section-top">
        <img src="{% static 'img/fon1.jpg' %}" class="img-responsive img-rounded">
    </div>

{% endblock %}

blok2/templates/account_user.html
<!-- Страница для просмотра,редактирования учетных данных(Имя,Фамилия,Адрес,Дата рождения) вызываемая из navbar_kab.html или navbar_kaba.html -->
<!-- вызов страницы прописан в urls.py , обработка формы(forms.py) прописана в views.py-->
{% extends 'base.html' %} <!-- наследуемся(вставка в base блока content) от основного шаблона base.html (верх,основа,футер) -->
{% load static %} <!-- обращаемся в каталог static где наши jpg и css -->
{% block title %}Учетные данные{% endblock %}

{% block content %}
{% if user.is_superuser == 1 %}
   {% include 'navbar_kaba.html' %} <!-- Меню администратора -->
{% else %}
   {% include 'navbar_kab.html' %} <!-- Меню пользователя -->
{% endif %}
{% if user.is_authenticated %}
   <div class="container section-top">
        <div class="row">
            <div class="col-md-10 col-lg-offset-1"> <!-- количество колонок-->
             <br><h3 class="text-center">Учетные данные</h3><br>
                    <!-- передаем в views.py  в функцию Account_user форму ContactForm метод post, т.к. метод post то обязательно передаем csrf_token -->
                    <!-- csrf_token(передается в views.py) нужен django чтобы делать post запрос и проверять что запрос пришел именно с нашей страницы а не сторонний -->
                    <form class="form-horizontal" id=form_auth action="{% url 'Account_user' %}" method="post">{% csrf_token %}

                            <div class="form-group">
                                <div class="col-md-4">
                                    <label>Имя</label><span id="fn"> {{ user.first_name }}</span>
                                    <!-- form.first_name.errors глобальный тег проверки правильности ввода имени в поле имя -->
                                    <span class="form-error">{{ form.first_name.errors }}</span>
                                    <!-- form.first_name определяем в файле forms.py -->
                                    <input type="text" name="{{ form.first_name.html_name }}" class="form-control" id="fname"
                                        value="{{ request.POST.first_name }}"
                                    >
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-4">
                                    <!-- Присваиваем id="ln" для того чтобы в scripts_izreg.js менять имя при изменении через ajax -->
                                    <label>Фамилия</label><span id="ln"> {{ user.last_name }}</span>
                                    <!-- form.last_name.errors глобальный тег проверки правильности ввода фамилии в поле фамилия -->
                                    <span class="form-error">{{ form.last_name.errors }}</span>
                                    <!-- form.last_name определяем в файле forms.py -->
                                    <input type="text" name="{{ form.last_name.html_name }}" class="form-control" id="lname"
                                        value="{{ request.POST.last_name }}"
                                    >
                                </div>
                            </div>
                            <!--
                            <div class="form-group">
                                <div class="col-md-4">
                                    <label>Адрес</label><span id="lc"> {{ user.profile.location }}</span>
                                    <span class="form-error">{{ form.location.errors }}</span>
                                    <input type="text" name="{{ form.location.html_name }}" class="form-control" id="locat"
                                        value="{{ request.POST.location }}"
                                    >
                                </div>
                            </div>
                            -->
                            <div class="form-group">
                                <div class="col-md-4">
                                    <label>Дата рождения</label><span id="bd"> {{ user.profile.birth_date | date:"d-m-Y" }}</span>
                                    <span class="form-error">{{ form.birth_date.errors }}</span>
                                    <input type="date" name="{{ form.birth_date.html_name }}" class="form-control" id="bdate"
                                        value="{{ request.POST.birth_date }}"
                                    >
                                </div>
                            </div>

                        <hr>
                        <!-- type submit выполнение по событию -->
                        <!-- По id="auth_user" в scripts_izreg.js выполняется функция userIzm изменения учетных данных -->
                        <!-- Стиль Кнопки меняем на закругленный в обьеме и отступами  section-top в style.css -->
                        <div class="text-right">
                            <button type="submit" id="auth_user" class="btn btn-primary btn-md section-top">Изменить</button>
                        </div>

                    </form>
            </div>

        </div>
    </div>
{% endif %}
{% endblock %}

blok2/templates/exchange_list.html
<!-- Страница для просмотра,редактирования списка заявок на обмен таблицы БД Exchange_List blok2/models.py вызываемая из navbar_kaba.html -->
<!-- Отображаем таблицу с помощью плагина datatables.net, подключаем плагин и его стили в blok1/base.html -->
<!-- Дополнительно используем фрэймворк rest framework, pip install djangorestframework, pip install django-model-utils -->
<!-- В settings.py подключаем в INSTALLED_APPS фрэймворк 'rest_framework' -->
<!-- вызов страницы прописан в blok2/views.py функцией PricesCurrency через blok2/urls.py -->
<!-- обработка таблицы и всплывающих форм через скрипт js/table_exchange_list.js методом ajax-->
<!-- используем маршрутизатор DefaultRouter фрэймворка rest framework в chgskv/urls.py -->
{% extends 'base.html' %} <!-- наследуемся(вставка в base блока content) от основного шаблона base.html (верх,основа,футер) -->
{% load static %} <!-- обращаемся в каталог static где наши jpg и css -->
{% block title %}Справочник списка заявок на обмен{% endblock %}

{% block menu_kab %}
    {% if user.is_superuser == 1 %}
       {% include 'navbar_kaba.html' %} <!-- Меню администратора -->
    {% else %}
       {% include 'navbar_kab.html' %} <!-- Меню пользователя -->
    {% endif %}
{% endblock menu_kab %}

{% block content %}
{% if user.is_superuser == 1 %}
<div class="container">

    <div class="jumbotron">
        <h3 class="text-center">Справочник списка заявок на обмен</h3>
    </div>

    <!-- New  button -->
    <div class="text-center">
        <button type="button" data-dismiss="modal" class="btn btn-primary btn-md" id="new">Новая запись</button>
    </div>
    <br>
    <!-- datatables action="/path/to/your/script" {% csrf_token %} -->
    <form id="frm-datatables" method="POST">{% csrf_token %}
        <table id="datatables" class="table table-hover">
            <thead>
            <tr>
                <th><input type="checkbox" name="select_all" value="1" id="example-select-all"></th>
                <th>id</th>
                <th>id клиента</th>
                <th>id пары валют</th>
                <th>id покупаемой валюты</th>
                <th>наименование покупаемой валюты</th>
                <th>сумма покупки</th>
                <th>кошелек(счет) клиента отдает</th>
                <th>id продаваемой валюты</th>
                <th>наименование продаваемой валюты</th>
                <th>сумма продажи</th>
                <th>кошелек(счет) клиента получает</th>
                <th>курс продажи клиенту</th>
                <th>курс покупки на бирже факт</th>
                <th>сумма покупки факт</th>
                <th>кошелек(счет) биржи</th>
                <th>статус заявки</th>
                <th>Активный</th>
                <th>Создан</th>
                <th>Изменен</th>
                <th>Действие</th>
            </tr>
            </thead>
            <tfoot>
            <tr>

            </tr>
            </tfoot>
        </table>
        <br>
    <p><button class="btn btn-success">Удалить группу</button></p>
    <!--  id="chekbox" значение в table_prices_currency.js
    <b>Отправка на сервер для обработки выбора чекбокс:</b><br>
    <pre id="chekbox">
    </pre> -->
    </form>


    <!-- NEW and EDIT Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="modal_title"></h4>
                </div>
                <div class="modal-body">
                    <form role="form" id="token">{% csrf_token %}
                        <div class="form-group">
                            <label for="id_user"><span class="glyphicon glyphicon-pencil"></span> id пользователя</label>
                            <input type="number" class="form-control" id="id_user" name="id_user" placeholder="Enter Id User"
                                   required maxlength="10">
                        </div>
                        <div class="form-group">
                            <label for="id_pair_market"><span class="glyphicon glyphicon-pencil"></span> id пары валют</label>
                            <input type="number" class="form-control" id="id_pair_market" name="id_pair_market" placeholder="Enter Id pair currency"
                                   required maxlength="10">
                        </div>
                        <div class="form-group">
                            <label for="name_currency_buy_id"><span class="glyphicon glyphicon-pencil"></span> id покупаемой валюты</label>
                            <input type="number" class="form-control" id="name_currency_buy_id" name="name_currency_buy_id" placeholder="Enter Id buy currency"
                                   required maxlength="10">
                        </div>
                        <div class="form-group">
                            <label for="name_currency_buy_currency"><span class="glyphicon glyphicon-pencil"></span> покупаемая валюта</label>
                            <input type="text" class="form-control" id="name_currency_buy_currency" name="name_currency_buy_currency" placeholder="Enter buy currency"
                                   required maxlength="30">
                        </div>
                        <div class="form-group">
                            <label for="sum_currency_buy"><span class="glyphicon glyphicon-pencil"></span> сумма покупки</label>
                            <input type="number" class="form-control" id="sum_currency_buy" name="sum_currency_buy"
                                   step="0.00000001" min="0" max="999999999999" placeholder="0.00000000" required>
                        </div>
                        <div class="form-group">
                            <label for="wallet_currency_buy"><span class="glyphicon glyphicon-pencil"></span> кошелек(счет) клиента отдает</label>
                            <input type="text" class="form-control" id="wallet_currency_buy" name="wallet_currency_buy"
                                   placeholder="Enter Кошелек(счет)" required maxlength="80">
                        </div>
                        <div class="form-group">
                            <label for="name_currency_sell_id"><span class="glyphicon glyphicon-pencil"></span> id продаваемой валюты</label>
                            <input type="number" class="form-control" id="name_currency_sell_id" name="name_currency_sell_id" placeholder="Enter Id sell currency"
                                   required maxlength="10">
                        </div>
                        <div class="form-group">
                            <label for="name_currency_sell_currency"><span class="glyphicon glyphicon-pencil"></span> продаваемая валюта</label>
                            <input type="text" class="form-control" id="name_currency_sell_currency" name="name_currency_sell_currency" placeholder="Enter sell currency"
                                   required maxlength="30">
                        </div>
                        <div class="form-group">
                            <label for="sum_currency_sell"><span class="glyphicon glyphicon-pencil"></span> сумма продажи</label>
                            <input type="number" class="form-control" id="sum_currency_sell" name="sum_currency_sell"
                                   step="0.00000001" min="0" max="999999999999" placeholder="0.00000000" required>
                        </div>
                        <div class="form-group">
                            <label for="wallet_currency_sell"><span class="glyphicon glyphicon-pencil"></span> кошелек(счет) клиента получает</label>
                            <input type="text" class="form-control" id="wallet_currency_sell" name="wallet_currency_sell"
                                   placeholder="Enter Кошелек(счет)" required maxlength="80">
                        </div>
                        <div class="form-group">
                            <label for="kurs_sell"><span class="glyphicon glyphicon-file"></span> курс продажи клиенту</label>
                            <input type="number" class="form-control" id="kurs_sell" name="kurs_sell"
                                   step="0.00000001" min="0" max="99999999999" placeholder="0.00000000" required>
                        </div>
                        <div class="form-group">
                            <label for="kurs_buy_fact"><span class="glyphicon glyphicon-file"></span> курс покупки на бирже факт</label>
                            <input type="number" class="form-control" id="kurs_buy_fact" name="kurs_buy_fact"
                                   step="0.00000001" min="0" max="99999999999" placeholder="0.00000000" required>
                        </div>
                        <div class="form-group">
                            <label for="sum_currency_buy_fact"><span class="glyphicon glyphicon-file"></span> сумма покупки факт</label>
                            <input type="number" class="form-control" id="sum_currency_buy_fact" name="sum_currency_buy_fact"
                                   step="0.00000001" min="0" max="99999999999" placeholder="0.00000000" required>
                        </div>
                        <div class="form-group">
                            <label for="wallet_fact"><span class="glyphicon glyphicon-pencil"></span> кошелек(счет) биржи</label>
                            <input type="text" class="form-control" id="wallet_fact" name="wallet_fact"
                                   placeholder="Enter Кошелек(счет)" required maxlength="80">
                        </div>
                        <div class="form-group">
                            <label for="status"><span class="glyphicon glyphicon-pencil"></span> статус заявки(0-удалена,1-ожидает оплаты,2-исполнена)</label>
                            <input type="number" class="form-control" id="status" name="id_user" placeholder="Enter Status 1,2,3"
                                   required maxlength="10">
                        </div>
                        <div class="form-group">
                        <label for="is_active"><span class="glyphicon glyphicon-file"></span> Активный</label>
                        <select id="is_active" name="is_active">
                        <option value=1>Да</option>
                        <option value=0>Нет</option>
                        </select>
                        </div>
                        <input type="hidden" id="type" name="type" value="">
                        <button type="submit" class="btn btn-success btn-block"><span
                                class="glyphicon glyphicon-ok"></span> OK
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Delete Modal -->
    <div class="modal fade" id="confirm" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Вы уверенны?</h4>
                </div>
                <div class="modal-body">
                    <button type="button" data-dismiss="modal" class="btn btn-primary" id="delete">Удалить</button>
                    <button type="button" data-dismiss="modal" class="btn">Редактировать</button>
                </div>
            </div>
        </div>
    </div>

</div>
{% endif %}

{% endblock %}

{% block js_stuff %}

<!-- Подключаем скрипт для таблицы БД наименования валют плагина datatables.net -->

<script src="{% static 'js/table_exchange_list.js' %}"></script>

{% endblock js_stuff %}

blok2/templates/report1.html
<!-- не использую для таблиц плагина datatables, т.к. в нём есть функция печати -->
{% extends 'base.html' %} <!-- наследуемся(вставка в base блока content) от основного шаблона base.html (верх,основа,футер) -->
{% load static %} <!-- обращаемся в каталог static где наши jpg и css -->


{% block content %}

<div class="container">
    <div class="jumbotron">
        <h3 class="text-center" id="print-title">Справочник наименования валют</h3>
    </div>

    <!-- datatables -->
    <div id="print-tables">
    <table class="table table-hover" >
        <thead>
        <tr>
            <th>id</th>
            <th>Валюта</th>
            <th>Символ</th>
            <th>Активный</th>
            <th>Создан</th>
            <th>Изменен</th>
            <th>Действие</th>
        </tr>
        </thead>
        <tfoot>
        <tr>

        </tr>
        </tfoot>
    </table>
    </div>
    <br>
    <div class="text-left">
        <!-- функция callPrint() из table_name_currency.js -->
        <form onclick="javascript:callPrint();" method="post">{% csrf_token %}
            <button  class="btn btn-success btn-md" >Печать</button>
        </form>

    </div>
</div>


{% endblock %}

{% block js_stuff %}

<!-- Подключаем скрипт для таблицы БД наименования валют плагина datatables.net -->

<script src="{% static 'js/table_name_currency.js' %}"></script>

{% endblock js_stuff %}